#!/usr/bin/env python3
import requests
import sys
from bs4 import BeautifulSoup


args = " ".join(sys.argv[1:])
if not args:
    sys.exit(1)

url = "https://search.azlyrics.com/suggest.php?q=%s" % args
search_term = requests.get(url).json()
if not search_term["term"]:
    sys.exit(1)

suggestions = search_term["songs"]

if suggestions:
    resp = requests.get(suggestions[0]["url"])
    lyrics_page = BeautifulSoup(resp.content, "lxml")

    lyrics_container = lyrics_page.find("div", attrs={"class": "ringtone"}).parent
    lyrics_header = suggestions[0]["autocomplete"]
    lyrics_text = lyrics_container.find("div", attrs={"class": ""}).text.strip()

    print(lyrics_header, end="\n\n")
    print(lyrics_text)
    sys.exit(0)
else:
    sys.exit(1)
